### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Zoogoumafou** [sch3m4/androidpatternlock#9]
```
sudo python3 aplc.py gesture.sample.key 

################################
# Android Pattern Lock Cracker #
#             v0.2             #
# ---------------------------- #
#  Written by Chema Garcia     #
#     http://safetybits.net    #
#     chema@safetybits.net     #
#          @sch3m4             #
################################

[i] Taken from: http://forensics.spreitzenbarth.de/2012/02/28/cracking-the-pattern-lock-on-android/

Traceback (most recent call last):
  File "/home/htb-onibi/androidpatternlock/aplc.py", line 178, in <module>
    main()
  File "/home/htb-onibi/androidpatternlock/aplc.py", line 152, in main
    gest = f.read(hashlib.sha1().digest_size).encode('hex')
AttributeError: 'bytes' object has no attribute 'encode'

```

I don't know whats cause that and how to solve it

**Comment by TheMythologist** [comment]
Replace:
```python
gest = f.read(hashlib.sha1().digest_size).encode('hex')
```
with:
```python
gest = f.read(hashlib.sha1().digest_size).hex()
```
